# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    gym(export_method: "development")
  end
end

platform :ios do
    desc "Mirrortracing"
    lane :firebase_ios do
        increment_build_number
        gym(export_method: "development")
        firebase_app_distribution(
            app: "1:962139002233:ios:888ab0edb960d6a15f8ba8",
            testers: "iamlien@gmail.com, lcbc.app.dev@gmail.com",
            release_notes: "Second release!",
        )

    end
end